CONNECTION_URL=jdbc:mariadb://localhost:3306/frutta_srl
LOGIN_USER=login
LOGIN_PASS=login
OPERATORE_VENDITE_USER=operatore_vendite
OPERATORE_VENDITE_PASS=operatore
MAGAZZINIERE_USER=magazziniere
MAGAZZINIERE_PASS=magazziniere