CONNECTION_URL=jdbc:mariadb://localhost:3306/frutta_srl
LOGIN_USER=login
LOGIN_PASS=login
OPERATORE_VENDITE_USER=operatore_vendite
OPERATORE_VENDITE_PASS=operatore_vendite
MAGAZZINIERE_USER=magazziniere
MAGAZZINIERE_PASS=magazziniere